# Generated by Django 5.2.1 on 2025-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_address_customuser_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IT", "Công nghệ thông tin"),
                    ("HR", "Nhân sự"),
                    ("Finance", "Tài chính"),
                    ("Marketing", "Marketing"),
                ],
                default="",
                help_text="Phòng ban trong công ty",
                max_length=100,
            ),
        ),
    ]
