# Generated by Django 5.2.1 on 2025-05-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_rename_position_jobrequest_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.jobposting",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Đang xử lý"),
                    ("accepted", "Đậu"),
                    ("rejected", "Trượt"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
