# Generated by Django 5.2.1 on 2025-05-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_remove_jobrequest_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobrequest",
            name="actionlog",
        ),
        migrations.AddField(
            model_name="jobrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ duyệt"),
                    ("approved", "Đã duyệt"),
                    ("rejected", "Từ chối"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
