# Generated by Django 5.2.1 on 2025-05-30 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_remove_jobrequest_actionlog_jobrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="job_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_logs",
                to="jobs.jobrequest",
            ),
        ),
    ]
