# Generated by Django 5.2.1 on 2025-05-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_companyinfo_logo_companyinfo_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyinfo",
            options={
                "verbose_name": "Thông tin doanh nghiệp",
                "verbose_name_plural": "Thông tin doanh nghiệp",
            },
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="website",
            field=models.URLField(),
        ),
    ]
