# Generated by Django 5.2.1 on 2025-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_interviewer",
            field=models.BooleanField(
                default=False,
                help_text="Xác định người dùng có thể làm người phỏng vấn",
            ),
        ),
    ]
